import os
import json
from glob import glob

conf = json.loads(open('../../config.json').read())

env = Environment(
    CXXFLAGS=conf['CXXFLAGS'],
    CCFLAGS=conf['CCFLAGS'],
    LINKFLAGS=conf['LINKFLAGS'],
    CC=conf['CC'],
    CXX=conf['CXX'],
    SHLIBPREFIX=conf['SHLIBPREFIX'],
    tools=conf['TOOLS'],
)

shlib = env.SharedLibrary("lib/JSON" + conf['TORA_EXTSUFFIX'], ['json.cc'])
Default(shlib)

env.Command('test', shlib, "prove --exec '../../bin/tora -I lib -I ../../lib/' t/*.tra")

PREFIX=conf['PREFIX']

installs = []
for x in os.listdir('lib/'):
    dst = conf['TORA_LIBPREFIX'] + x
    src = "lib/" + x
    installs += [env.InstallAs(dst, src)]

env.Alias('install', [shlib, installs])

