# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tokuhirom/dev/tora

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tokuhirom/dev/tora

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tokuhirom/dev/tora/CMakeFiles /home/tokuhirom/dev/tora/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tokuhirom/dev/tora/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lemon

# Build rule for target.
lemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lemon
.PHONY : lemon

# fast build rule for target.
lemon/fast:
	$(MAKE) -f CMakeFiles/lemon.dir/build.make CMakeFiles/lemon.dir/build
.PHONY : lemon/fast

#=============================================================================
# Target rules for targets named libtora_a

# Build rule for target.
libtora_a: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libtora_a
.PHONY : libtora_a

# fast build rule for target.
libtora_a/fast:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/build
.PHONY : libtora_a/fast

#=============================================================================
# Target rules for targets named libtora_so

# Build rule for target.
libtora_so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libtora_so
.PHONY : libtora_so

# fast build rule for target.
libtora_so/fast:
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/build
.PHONY : libtora_so/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named tests/test_compiler.t

# Build rule for target.
tests/test_compiler.t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_compiler.t
.PHONY : tests/test_compiler.t

# fast build rule for target.
tests/test_compiler.t/fast:
	$(MAKE) -f CMakeFiles/tests/test_compiler.t.dir/build.make CMakeFiles/tests/test_compiler.t.dir/build
.PHONY : tests/test_compiler.t/fast

#=============================================================================
# Target rules for targets named tests/test_hexchar2int.t

# Build rule for target.
tests/test_hexchar2int.t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_hexchar2int.t
.PHONY : tests/test_hexchar2int.t

# fast build rule for target.
tests/test_hexchar2int.t/fast:
	$(MAKE) -f CMakeFiles/tests/test_hexchar2int.t.dir/build.make CMakeFiles/tests/test_hexchar2int.t.dir/build
.PHONY : tests/test_hexchar2int.t/fast

#=============================================================================
# Target rules for targets named tests/test_inspector.t

# Build rule for target.
tests/test_inspector.t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_inspector.t
.PHONY : tests/test_inspector.t

# fast build rule for target.
tests/test_inspector.t/fast:
	$(MAKE) -f CMakeFiles/tests/test_inspector.t.dir/build.make CMakeFiles/tests/test_inspector.t.dir/build
.PHONY : tests/test_inspector.t/fast

#=============================================================================
# Target rules for targets named tests/test_lexer.t

# Build rule for target.
tests/test_lexer.t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_lexer.t
.PHONY : tests/test_lexer.t

# fast build rule for target.
tests/test_lexer.t/fast:
	$(MAKE) -f CMakeFiles/tests/test_lexer.t.dir/build.make CMakeFiles/tests/test_lexer.t.dir/build
.PHONY : tests/test_lexer.t/fast

#=============================================================================
# Target rules for targets named tests/test_lexical_frame.t

# Build rule for target.
tests/test_lexical_frame.t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_lexical_frame.t
.PHONY : tests/test_lexical_frame.t

# fast build rule for target.
tests/test_lexical_frame.t/fast:
	$(MAKE) -f CMakeFiles/tests/test_lexical_frame.t.dir/build.make CMakeFiles/tests/test_lexical_frame.t.dir/build
.PHONY : tests/test_lexical_frame.t/fast

#=============================================================================
# Target rules for targets named tests/test_pad_list.t

# Build rule for target.
tests/test_pad_list.t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_pad_list.t
.PHONY : tests/test_pad_list.t

# fast build rule for target.
tests/test_pad_list.t/fast:
	$(MAKE) -f CMakeFiles/tests/test_pad_list.t.dir/build.make CMakeFiles/tests/test_pad_list.t.dir/build
.PHONY : tests/test_pad_list.t/fast

#=============================================================================
# Target rules for targets named tests/test_split_package.t

# Build rule for target.
tests/test_split_package.t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_split_package.t
.PHONY : tests/test_split_package.t

# fast build rule for target.
tests/test_split_package.t/fast:
	$(MAKE) -f CMakeFiles/tests/test_split_package.t.dir/build.make CMakeFiles/tests/test_split_package.t.dir/build
.PHONY : tests/test_split_package.t/fast

#=============================================================================
# Target rules for targets named tests/test_value.t

# Build rule for target.
tests/test_value.t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_value.t
.PHONY : tests/test_value.t

# fast build rule for target.
tests/test_value.t/fast:
	$(MAKE) -f CMakeFiles/tests/test_value.t.dir/build.make CMakeFiles/tests/test_value.t.dir/build
.PHONY : tests/test_value.t/fast

#=============================================================================
# Target rules for targets named tests/test_value_array.t

# Build rule for target.
tests/test_value_array.t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_value_array.t
.PHONY : tests/test_value_array.t

# fast build rule for target.
tests/test_value_array.t/fast:
	$(MAKE) -f CMakeFiles/tests/test_value_array.t.dir/build.make CMakeFiles/tests/test_value_array.t.dir/build
.PHONY : tests/test_value_array.t/fast

#=============================================================================
# Target rules for targets named tests/test_value_code.t

# Build rule for target.
tests/test_value_code.t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_value_code.t
.PHONY : tests/test_value_code.t

# fast build rule for target.
tests/test_value_code.t/fast:
	$(MAKE) -f CMakeFiles/tests/test_value_code.t.dir/build.make CMakeFiles/tests/test_value_code.t.dir/build
.PHONY : tests/test_value_code.t/fast

#=============================================================================
# Target rules for targets named tests/test_value_op.t

# Build rule for target.
tests/test_value_op.t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_value_op.t
.PHONY : tests/test_value_op.t

# fast build rule for target.
tests/test_value_op.t/fast:
	$(MAKE) -f CMakeFiles/tests/test_value_op.t.dir/build.make CMakeFiles/tests/test_value_op.t.dir/build
.PHONY : tests/test_value_op.t/fast

#=============================================================================
# Target rules for targets named toraexe

# Build rule for target.
toraexe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 toraexe
.PHONY : toraexe

# fast build rule for target.
toraexe/fast:
	$(MAKE) -f CMakeFiles/toraexe.dir/build.make CMakeFiles/toraexe.dir/build
.PHONY : toraexe/fast

tests/test_compiler.o: tests/test_compiler.cc.o
.PHONY : tests/test_compiler.o

# target to build an object file
tests/test_compiler.cc.o:
	$(MAKE) -f CMakeFiles/tests/test_compiler.t.dir/build.make CMakeFiles/tests/test_compiler.t.dir/tests/test_compiler.cc.o
.PHONY : tests/test_compiler.cc.o

tests/test_compiler.i: tests/test_compiler.cc.i
.PHONY : tests/test_compiler.i

# target to preprocess a source file
tests/test_compiler.cc.i:
	$(MAKE) -f CMakeFiles/tests/test_compiler.t.dir/build.make CMakeFiles/tests/test_compiler.t.dir/tests/test_compiler.cc.i
.PHONY : tests/test_compiler.cc.i

tests/test_compiler.s: tests/test_compiler.cc.s
.PHONY : tests/test_compiler.s

# target to generate assembly for a file
tests/test_compiler.cc.s:
	$(MAKE) -f CMakeFiles/tests/test_compiler.t.dir/build.make CMakeFiles/tests/test_compiler.t.dir/tests/test_compiler.cc.s
.PHONY : tests/test_compiler.cc.s

tests/test_hexchar2int.o: tests/test_hexchar2int.cc.o
.PHONY : tests/test_hexchar2int.o

# target to build an object file
tests/test_hexchar2int.cc.o:
	$(MAKE) -f CMakeFiles/tests/test_hexchar2int.t.dir/build.make CMakeFiles/tests/test_hexchar2int.t.dir/tests/test_hexchar2int.cc.o
.PHONY : tests/test_hexchar2int.cc.o

tests/test_hexchar2int.i: tests/test_hexchar2int.cc.i
.PHONY : tests/test_hexchar2int.i

# target to preprocess a source file
tests/test_hexchar2int.cc.i:
	$(MAKE) -f CMakeFiles/tests/test_hexchar2int.t.dir/build.make CMakeFiles/tests/test_hexchar2int.t.dir/tests/test_hexchar2int.cc.i
.PHONY : tests/test_hexchar2int.cc.i

tests/test_hexchar2int.s: tests/test_hexchar2int.cc.s
.PHONY : tests/test_hexchar2int.s

# target to generate assembly for a file
tests/test_hexchar2int.cc.s:
	$(MAKE) -f CMakeFiles/tests/test_hexchar2int.t.dir/build.make CMakeFiles/tests/test_hexchar2int.t.dir/tests/test_hexchar2int.cc.s
.PHONY : tests/test_hexchar2int.cc.s

tests/test_inspector.o: tests/test_inspector.cc.o
.PHONY : tests/test_inspector.o

# target to build an object file
tests/test_inspector.cc.o:
	$(MAKE) -f CMakeFiles/tests/test_inspector.t.dir/build.make CMakeFiles/tests/test_inspector.t.dir/tests/test_inspector.cc.o
.PHONY : tests/test_inspector.cc.o

tests/test_inspector.i: tests/test_inspector.cc.i
.PHONY : tests/test_inspector.i

# target to preprocess a source file
tests/test_inspector.cc.i:
	$(MAKE) -f CMakeFiles/tests/test_inspector.t.dir/build.make CMakeFiles/tests/test_inspector.t.dir/tests/test_inspector.cc.i
.PHONY : tests/test_inspector.cc.i

tests/test_inspector.s: tests/test_inspector.cc.s
.PHONY : tests/test_inspector.s

# target to generate assembly for a file
tests/test_inspector.cc.s:
	$(MAKE) -f CMakeFiles/tests/test_inspector.t.dir/build.make CMakeFiles/tests/test_inspector.t.dir/tests/test_inspector.cc.s
.PHONY : tests/test_inspector.cc.s

tests/test_lexer.o: tests/test_lexer.cc.o
.PHONY : tests/test_lexer.o

# target to build an object file
tests/test_lexer.cc.o:
	$(MAKE) -f CMakeFiles/tests/test_lexer.t.dir/build.make CMakeFiles/tests/test_lexer.t.dir/tests/test_lexer.cc.o
.PHONY : tests/test_lexer.cc.o

tests/test_lexer.i: tests/test_lexer.cc.i
.PHONY : tests/test_lexer.i

# target to preprocess a source file
tests/test_lexer.cc.i:
	$(MAKE) -f CMakeFiles/tests/test_lexer.t.dir/build.make CMakeFiles/tests/test_lexer.t.dir/tests/test_lexer.cc.i
.PHONY : tests/test_lexer.cc.i

tests/test_lexer.s: tests/test_lexer.cc.s
.PHONY : tests/test_lexer.s

# target to generate assembly for a file
tests/test_lexer.cc.s:
	$(MAKE) -f CMakeFiles/tests/test_lexer.t.dir/build.make CMakeFiles/tests/test_lexer.t.dir/tests/test_lexer.cc.s
.PHONY : tests/test_lexer.cc.s

tests/test_lexical_frame.o: tests/test_lexical_frame.cc.o
.PHONY : tests/test_lexical_frame.o

# target to build an object file
tests/test_lexical_frame.cc.o:
	$(MAKE) -f CMakeFiles/tests/test_lexical_frame.t.dir/build.make CMakeFiles/tests/test_lexical_frame.t.dir/tests/test_lexical_frame.cc.o
.PHONY : tests/test_lexical_frame.cc.o

tests/test_lexical_frame.i: tests/test_lexical_frame.cc.i
.PHONY : tests/test_lexical_frame.i

# target to preprocess a source file
tests/test_lexical_frame.cc.i:
	$(MAKE) -f CMakeFiles/tests/test_lexical_frame.t.dir/build.make CMakeFiles/tests/test_lexical_frame.t.dir/tests/test_lexical_frame.cc.i
.PHONY : tests/test_lexical_frame.cc.i

tests/test_lexical_frame.s: tests/test_lexical_frame.cc.s
.PHONY : tests/test_lexical_frame.s

# target to generate assembly for a file
tests/test_lexical_frame.cc.s:
	$(MAKE) -f CMakeFiles/tests/test_lexical_frame.t.dir/build.make CMakeFiles/tests/test_lexical_frame.t.dir/tests/test_lexical_frame.cc.s
.PHONY : tests/test_lexical_frame.cc.s

tests/test_pad_list.o: tests/test_pad_list.cc.o
.PHONY : tests/test_pad_list.o

# target to build an object file
tests/test_pad_list.cc.o:
	$(MAKE) -f CMakeFiles/tests/test_pad_list.t.dir/build.make CMakeFiles/tests/test_pad_list.t.dir/tests/test_pad_list.cc.o
.PHONY : tests/test_pad_list.cc.o

tests/test_pad_list.i: tests/test_pad_list.cc.i
.PHONY : tests/test_pad_list.i

# target to preprocess a source file
tests/test_pad_list.cc.i:
	$(MAKE) -f CMakeFiles/tests/test_pad_list.t.dir/build.make CMakeFiles/tests/test_pad_list.t.dir/tests/test_pad_list.cc.i
.PHONY : tests/test_pad_list.cc.i

tests/test_pad_list.s: tests/test_pad_list.cc.s
.PHONY : tests/test_pad_list.s

# target to generate assembly for a file
tests/test_pad_list.cc.s:
	$(MAKE) -f CMakeFiles/tests/test_pad_list.t.dir/build.make CMakeFiles/tests/test_pad_list.t.dir/tests/test_pad_list.cc.s
.PHONY : tests/test_pad_list.cc.s

tests/test_split_package.o: tests/test_split_package.cc.o
.PHONY : tests/test_split_package.o

# target to build an object file
tests/test_split_package.cc.o:
	$(MAKE) -f CMakeFiles/tests/test_split_package.t.dir/build.make CMakeFiles/tests/test_split_package.t.dir/tests/test_split_package.cc.o
.PHONY : tests/test_split_package.cc.o

tests/test_split_package.i: tests/test_split_package.cc.i
.PHONY : tests/test_split_package.i

# target to preprocess a source file
tests/test_split_package.cc.i:
	$(MAKE) -f CMakeFiles/tests/test_split_package.t.dir/build.make CMakeFiles/tests/test_split_package.t.dir/tests/test_split_package.cc.i
.PHONY : tests/test_split_package.cc.i

tests/test_split_package.s: tests/test_split_package.cc.s
.PHONY : tests/test_split_package.s

# target to generate assembly for a file
tests/test_split_package.cc.s:
	$(MAKE) -f CMakeFiles/tests/test_split_package.t.dir/build.make CMakeFiles/tests/test_split_package.t.dir/tests/test_split_package.cc.s
.PHONY : tests/test_split_package.cc.s

tests/test_value.o: tests/test_value.cc.o
.PHONY : tests/test_value.o

# target to build an object file
tests/test_value.cc.o:
	$(MAKE) -f CMakeFiles/tests/test_value.t.dir/build.make CMakeFiles/tests/test_value.t.dir/tests/test_value.cc.o
.PHONY : tests/test_value.cc.o

tests/test_value.i: tests/test_value.cc.i
.PHONY : tests/test_value.i

# target to preprocess a source file
tests/test_value.cc.i:
	$(MAKE) -f CMakeFiles/tests/test_value.t.dir/build.make CMakeFiles/tests/test_value.t.dir/tests/test_value.cc.i
.PHONY : tests/test_value.cc.i

tests/test_value.s: tests/test_value.cc.s
.PHONY : tests/test_value.s

# target to generate assembly for a file
tests/test_value.cc.s:
	$(MAKE) -f CMakeFiles/tests/test_value.t.dir/build.make CMakeFiles/tests/test_value.t.dir/tests/test_value.cc.s
.PHONY : tests/test_value.cc.s

tests/test_value_array.o: tests/test_value_array.cc.o
.PHONY : tests/test_value_array.o

# target to build an object file
tests/test_value_array.cc.o:
	$(MAKE) -f CMakeFiles/tests/test_value_array.t.dir/build.make CMakeFiles/tests/test_value_array.t.dir/tests/test_value_array.cc.o
.PHONY : tests/test_value_array.cc.o

tests/test_value_array.i: tests/test_value_array.cc.i
.PHONY : tests/test_value_array.i

# target to preprocess a source file
tests/test_value_array.cc.i:
	$(MAKE) -f CMakeFiles/tests/test_value_array.t.dir/build.make CMakeFiles/tests/test_value_array.t.dir/tests/test_value_array.cc.i
.PHONY : tests/test_value_array.cc.i

tests/test_value_array.s: tests/test_value_array.cc.s
.PHONY : tests/test_value_array.s

# target to generate assembly for a file
tests/test_value_array.cc.s:
	$(MAKE) -f CMakeFiles/tests/test_value_array.t.dir/build.make CMakeFiles/tests/test_value_array.t.dir/tests/test_value_array.cc.s
.PHONY : tests/test_value_array.cc.s

tests/test_value_code.o: tests/test_value_code.cc.o
.PHONY : tests/test_value_code.o

# target to build an object file
tests/test_value_code.cc.o:
	$(MAKE) -f CMakeFiles/tests/test_value_code.t.dir/build.make CMakeFiles/tests/test_value_code.t.dir/tests/test_value_code.cc.o
.PHONY : tests/test_value_code.cc.o

tests/test_value_code.i: tests/test_value_code.cc.i
.PHONY : tests/test_value_code.i

# target to preprocess a source file
tests/test_value_code.cc.i:
	$(MAKE) -f CMakeFiles/tests/test_value_code.t.dir/build.make CMakeFiles/tests/test_value_code.t.dir/tests/test_value_code.cc.i
.PHONY : tests/test_value_code.cc.i

tests/test_value_code.s: tests/test_value_code.cc.s
.PHONY : tests/test_value_code.s

# target to generate assembly for a file
tests/test_value_code.cc.s:
	$(MAKE) -f CMakeFiles/tests/test_value_code.t.dir/build.make CMakeFiles/tests/test_value_code.t.dir/tests/test_value_code.cc.s
.PHONY : tests/test_value_code.cc.s

tests/test_value_op.o: tests/test_value_op.cc.o
.PHONY : tests/test_value_op.o

# target to build an object file
tests/test_value_op.cc.o:
	$(MAKE) -f CMakeFiles/tests/test_value_op.t.dir/build.make CMakeFiles/tests/test_value_op.t.dir/tests/test_value_op.cc.o
.PHONY : tests/test_value_op.cc.o

tests/test_value_op.i: tests/test_value_op.cc.i
.PHONY : tests/test_value_op.i

# target to preprocess a source file
tests/test_value_op.cc.i:
	$(MAKE) -f CMakeFiles/tests/test_value_op.t.dir/build.make CMakeFiles/tests/test_value_op.t.dir/tests/test_value_op.cc.i
.PHONY : tests/test_value_op.cc.i

tests/test_value_op.s: tests/test_value_op.cc.s
.PHONY : tests/test_value_op.s

# target to generate assembly for a file
tests/test_value_op.cc.s:
	$(MAKE) -f CMakeFiles/tests/test_value_op.t.dir/build.make CMakeFiles/tests/test_value_op.t.dir/tests/test_value_op.cc.s
.PHONY : tests/test_value_op.cc.s

tools/lemon/lemon.o: tools/lemon/lemon.c.o
.PHONY : tools/lemon/lemon.o

# target to build an object file
tools/lemon/lemon.c.o:
	$(MAKE) -f CMakeFiles/lemon.dir/build.make CMakeFiles/lemon.dir/tools/lemon/lemon.c.o
.PHONY : tools/lemon/lemon.c.o

tools/lemon/lemon.i: tools/lemon/lemon.c.i
.PHONY : tools/lemon/lemon.i

# target to preprocess a source file
tools/lemon/lemon.c.i:
	$(MAKE) -f CMakeFiles/lemon.dir/build.make CMakeFiles/lemon.dir/tools/lemon/lemon.c.i
.PHONY : tools/lemon/lemon.c.i

tools/lemon/lemon.s: tools/lemon/lemon.c.s
.PHONY : tools/lemon/lemon.s

# target to generate assembly for a file
tools/lemon/lemon.c.s:
	$(MAKE) -f CMakeFiles/lemon.dir/build.make CMakeFiles/lemon.dir/tools/lemon/lemon.c.s
.PHONY : tools/lemon/lemon.c.s

tora/builtin.o: tora/builtin.cc.o
.PHONY : tora/builtin.o

# target to build an object file
tora/builtin.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/builtin.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/builtin.cc.o
.PHONY : tora/builtin.cc.o

tora/builtin.i: tora/builtin.cc.i
.PHONY : tora/builtin.i

# target to preprocess a source file
tora/builtin.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/builtin.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/builtin.cc.i
.PHONY : tora/builtin.cc.i

tora/builtin.s: tora/builtin.cc.s
.PHONY : tora/builtin.s

# target to generate assembly for a file
tora/builtin.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/builtin.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/builtin.cc.s
.PHONY : tora/builtin.cc.s

tora/compiler.o: tora/compiler.cc.o
.PHONY : tora/compiler.o

# target to build an object file
tora/compiler.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/compiler.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/compiler.cc.o
.PHONY : tora/compiler.cc.o

tora/compiler.i: tora/compiler.cc.i
.PHONY : tora/compiler.i

# target to preprocess a source file
tora/compiler.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/compiler.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/compiler.cc.i
.PHONY : tora/compiler.cc.i

tora/compiler.s: tora/compiler.cc.s
.PHONY : tora/compiler.s

# target to generate assembly for a file
tora/compiler.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/compiler.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/compiler.cc.s
.PHONY : tora/compiler.cc.s

tora/disasm.o: tora/disasm.cc.o
.PHONY : tora/disasm.o

# target to build an object file
tora/disasm.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/disasm.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/disasm.cc.o
.PHONY : tora/disasm.cc.o

tora/disasm.i: tora/disasm.cc.i
.PHONY : tora/disasm.i

# target to preprocess a source file
tora/disasm.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/disasm.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/disasm.cc.i
.PHONY : tora/disasm.cc.i

tora/disasm.s: tora/disasm.cc.s
.PHONY : tora/disasm.s

# target to generate assembly for a file
tora/disasm.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/disasm.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/disasm.cc.s
.PHONY : tora/disasm.cc.s

tora/frame.o: tora/frame.cc.o
.PHONY : tora/frame.o

# target to build an object file
tora/frame.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/frame.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/frame.cc.o
.PHONY : tora/frame.cc.o

tora/frame.i: tora/frame.cc.i
.PHONY : tora/frame.i

# target to preprocess a source file
tora/frame.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/frame.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/frame.cc.i
.PHONY : tora/frame.cc.i

tora/frame.s: tora/frame.cc.s
.PHONY : tora/frame.s

# target to generate assembly for a file
tora/frame.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/frame.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/frame.cc.s
.PHONY : tora/frame.cc.s

tora/inspector.o: tora/inspector.cc.o
.PHONY : tora/inspector.o

# target to build an object file
tora/inspector.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/inspector.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/inspector.cc.o
.PHONY : tora/inspector.cc.o

tora/inspector.i: tora/inspector.cc.i
.PHONY : tora/inspector.i

# target to preprocess a source file
tora/inspector.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/inspector.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/inspector.cc.i
.PHONY : tora/inspector.cc.i

tora/inspector.s: tora/inspector.cc.s
.PHONY : tora/inspector.s

# target to generate assembly for a file
tora/inspector.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/inspector.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/inspector.cc.s
.PHONY : tora/inspector.cc.s

tora/lexer.gen.o: tora/lexer.gen.cc.o
.PHONY : tora/lexer.gen.o

# target to build an object file
tora/lexer.gen.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/lexer.gen.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/lexer.gen.cc.o
.PHONY : tora/lexer.gen.cc.o

tora/lexer.gen.i: tora/lexer.gen.cc.i
.PHONY : tora/lexer.gen.i

# target to preprocess a source file
tora/lexer.gen.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/lexer.gen.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/lexer.gen.cc.i
.PHONY : tora/lexer.gen.cc.i

tora/lexer.gen.s: tora/lexer.gen.cc.s
.PHONY : tora/lexer.gen.s

# target to generate assembly for a file
tora/lexer.gen.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/lexer.gen.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/lexer.gen.cc.s
.PHONY : tora/lexer.gen.cc.s

tora/main.o: tora/main.cc.o
.PHONY : tora/main.o

# target to build an object file
tora/main.cc.o:
	$(MAKE) -f CMakeFiles/toraexe.dir/build.make CMakeFiles/toraexe.dir/tora/main.cc.o
.PHONY : tora/main.cc.o

tora/main.i: tora/main.cc.i
.PHONY : tora/main.i

# target to preprocess a source file
tora/main.cc.i:
	$(MAKE) -f CMakeFiles/toraexe.dir/build.make CMakeFiles/toraexe.dir/tora/main.cc.i
.PHONY : tora/main.cc.i

tora/main.s: tora/main.cc.s
.PHONY : tora/main.s

# target to generate assembly for a file
tora/main.cc.s:
	$(MAKE) -f CMakeFiles/toraexe.dir/build.make CMakeFiles/toraexe.dir/tora/main.cc.s
.PHONY : tora/main.cc.s

tora/node.o: tora/node.cc.o
.PHONY : tora/node.o

# target to build an object file
tora/node.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/node.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/node.cc.o
.PHONY : tora/node.cc.o

tora/node.i: tora/node.cc.i
.PHONY : tora/node.i

# target to preprocess a source file
tora/node.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/node.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/node.cc.i
.PHONY : tora/node.cc.i

tora/node.s: tora/node.cc.s
.PHONY : tora/node.s

# target to generate assembly for a file
tora/node.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/node.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/node.cc.s
.PHONY : tora/node.cc.s

tora/nodes.gen.o: tora/nodes.gen.cc.o
.PHONY : tora/nodes.gen.o

# target to build an object file
tora/nodes.gen.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/nodes.gen.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/nodes.gen.cc.o
.PHONY : tora/nodes.gen.cc.o

tora/nodes.gen.i: tora/nodes.gen.cc.i
.PHONY : tora/nodes.gen.i

# target to preprocess a source file
tora/nodes.gen.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/nodes.gen.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/nodes.gen.cc.i
.PHONY : tora/nodes.gen.cc.i

tora/nodes.gen.s: tora/nodes.gen.cc.s
.PHONY : tora/nodes.gen.s

# target to generate assembly for a file
tora/nodes.gen.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/nodes.gen.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/nodes.gen.cc.s
.PHONY : tora/nodes.gen.cc.s

tora/object.o: tora/object.cc.o
.PHONY : tora/object.o

# target to build an object file
tora/object.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object.cc.o
.PHONY : tora/object.cc.o

tora/object.i: tora/object.cc.i
.PHONY : tora/object.i

# target to preprocess a source file
tora/object.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object.cc.i
.PHONY : tora/object.cc.i

tora/object.s: tora/object.cc.s
.PHONY : tora/object.s

# target to generate assembly for a file
tora/object.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object.cc.s
.PHONY : tora/object.cc.s

tora/object/array.o: tora/object/array.cc.o
.PHONY : tora/object/array.o

# target to build an object file
tora/object/array.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/array.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/array.cc.o
.PHONY : tora/object/array.cc.o

tora/object/array.i: tora/object/array.cc.i
.PHONY : tora/object/array.i

# target to preprocess a source file
tora/object/array.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/array.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/array.cc.i
.PHONY : tora/object/array.cc.i

tora/object/array.s: tora/object/array.cc.s
.PHONY : tora/object/array.s

# target to generate assembly for a file
tora/object/array.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/array.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/array.cc.s
.PHONY : tora/object/array.cc.s

tora/object/bytes.o: tora/object/bytes.cc.o
.PHONY : tora/object/bytes.o

# target to build an object file
tora/object/bytes.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/bytes.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/bytes.cc.o
.PHONY : tora/object/bytes.cc.o

tora/object/bytes.i: tora/object/bytes.cc.i
.PHONY : tora/object/bytes.i

# target to preprocess a source file
tora/object/bytes.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/bytes.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/bytes.cc.i
.PHONY : tora/object/bytes.cc.i

tora/object/bytes.s: tora/object/bytes.cc.s
.PHONY : tora/object/bytes.s

# target to generate assembly for a file
tora/object/bytes.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/bytes.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/bytes.cc.s
.PHONY : tora/object/bytes.cc.s

tora/object/caller.o: tora/object/caller.cc.o
.PHONY : tora/object/caller.o

# target to build an object file
tora/object/caller.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/caller.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/caller.cc.o
.PHONY : tora/object/caller.cc.o

tora/object/caller.i: tora/object/caller.cc.i
.PHONY : tora/object/caller.i

# target to preprocess a source file
tora/object/caller.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/caller.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/caller.cc.i
.PHONY : tora/object/caller.cc.i

tora/object/caller.s: tora/object/caller.cc.s
.PHONY : tora/object/caller.s

# target to generate assembly for a file
tora/object/caller.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/caller.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/caller.cc.s
.PHONY : tora/object/caller.cc.s

tora/object/class.o: tora/object/class.cc.o
.PHONY : tora/object/class.o

# target to build an object file
tora/object/class.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/class.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/class.cc.o
.PHONY : tora/object/class.cc.o

tora/object/class.i: tora/object/class.cc.i
.PHONY : tora/object/class.i

# target to preprocess a source file
tora/object/class.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/class.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/class.cc.i
.PHONY : tora/object/class.cc.i

tora/object/class.s: tora/object/class.cc.s
.PHONY : tora/object/class.s

# target to generate assembly for a file
tora/object/class.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/class.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/class.cc.s
.PHONY : tora/object/class.cc.s

tora/object/code.o: tora/object/code.cc.o
.PHONY : tora/object/code.o

# target to build an object file
tora/object/code.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/code.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/code.cc.o
.PHONY : tora/object/code.cc.o

tora/object/code.i: tora/object/code.cc.i
.PHONY : tora/object/code.i

# target to preprocess a source file
tora/object/code.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/code.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/code.cc.i
.PHONY : tora/object/code.cc.i

tora/object/code.s: tora/object/code.cc.s
.PHONY : tora/object/code.s

# target to generate assembly for a file
tora/object/code.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/code.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/code.cc.s
.PHONY : tora/object/code.cc.s

tora/object/dir.o: tora/object/dir.cc.o
.PHONY : tora/object/dir.o

# target to build an object file
tora/object/dir.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/dir.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/dir.cc.o
.PHONY : tora/object/dir.cc.o

tora/object/dir.i: tora/object/dir.cc.i
.PHONY : tora/object/dir.i

# target to preprocess a source file
tora/object/dir.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/dir.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/dir.cc.i
.PHONY : tora/object/dir.cc.i

tora/object/dir.s: tora/object/dir.cc.s
.PHONY : tora/object/dir.s

# target to generate assembly for a file
tora/object/dir.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/dir.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/dir.cc.s
.PHONY : tora/object/dir.cc.s

tora/object/double.o: tora/object/double.cc.o
.PHONY : tora/object/double.o

# target to build an object file
tora/object/double.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/double.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/double.cc.o
.PHONY : tora/object/double.cc.o

tora/object/double.i: tora/object/double.cc.i
.PHONY : tora/object/double.i

# target to preprocess a source file
tora/object/double.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/double.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/double.cc.i
.PHONY : tora/object/double.cc.i

tora/object/double.s: tora/object/double.cc.s
.PHONY : tora/object/double.s

# target to generate assembly for a file
tora/object/double.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/double.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/double.cc.s
.PHONY : tora/object/double.cc.s

tora/object/dynaloader.o: tora/object/dynaloader.cc.o
.PHONY : tora/object/dynaloader.o

# target to build an object file
tora/object/dynaloader.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/dynaloader.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/dynaloader.cc.o
.PHONY : tora/object/dynaloader.cc.o

tora/object/dynaloader.i: tora/object/dynaloader.cc.i
.PHONY : tora/object/dynaloader.i

# target to preprocess a source file
tora/object/dynaloader.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/dynaloader.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/dynaloader.cc.i
.PHONY : tora/object/dynaloader.cc.i

tora/object/dynaloader.s: tora/object/dynaloader.cc.s
.PHONY : tora/object/dynaloader.s

# target to generate assembly for a file
tora/object/dynaloader.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/dynaloader.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/dynaloader.cc.s
.PHONY : tora/object/dynaloader.cc.s

tora/object/env.o: tora/object/env.cc.o
.PHONY : tora/object/env.o

# target to build an object file
tora/object/env.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/env.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/env.cc.o
.PHONY : tora/object/env.cc.o

tora/object/env.i: tora/object/env.cc.i
.PHONY : tora/object/env.i

# target to preprocess a source file
tora/object/env.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/env.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/env.cc.i
.PHONY : tora/object/env.cc.i

tora/object/env.s: tora/object/env.cc.s
.PHONY : tora/object/env.s

# target to generate assembly for a file
tora/object/env.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/env.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/env.cc.s
.PHONY : tora/object/env.cc.s

tora/object/file.o: tora/object/file.cc.o
.PHONY : tora/object/file.o

# target to build an object file
tora/object/file.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/file.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/file.cc.o
.PHONY : tora/object/file.cc.o

tora/object/file.i: tora/object/file.cc.i
.PHONY : tora/object/file.i

# target to preprocess a source file
tora/object/file.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/file.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/file.cc.i
.PHONY : tora/object/file.cc.i

tora/object/file.s: tora/object/file.cc.s
.PHONY : tora/object/file.s

# target to generate assembly for a file
tora/object/file.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/file.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/file.cc.s
.PHONY : tora/object/file.cc.s

tora/object/file_package.o: tora/object/file_package.cc.o
.PHONY : tora/object/file_package.o

# target to build an object file
tora/object/file_package.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/file_package.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/file_package.cc.o
.PHONY : tora/object/file_package.cc.o

tora/object/file_package.i: tora/object/file_package.cc.i
.PHONY : tora/object/file_package.i

# target to preprocess a source file
tora/object/file_package.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/file_package.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/file_package.cc.i
.PHONY : tora/object/file_package.cc.i

tora/object/file_package.s: tora/object/file_package.cc.s
.PHONY : tora/object/file_package.s

# target to generate assembly for a file
tora/object/file_package.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/file_package.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/file_package.cc.s
.PHONY : tora/object/file_package.cc.s

tora/object/hash.o: tora/object/hash.cc.o
.PHONY : tora/object/hash.o

# target to build an object file
tora/object/hash.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/hash.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/hash.cc.o
.PHONY : tora/object/hash.cc.o

tora/object/hash.i: tora/object/hash.cc.i
.PHONY : tora/object/hash.i

# target to preprocess a source file
tora/object/hash.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/hash.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/hash.cc.i
.PHONY : tora/object/hash.cc.i

tora/object/hash.s: tora/object/hash.cc.s
.PHONY : tora/object/hash.s

# target to generate assembly for a file
tora/object/hash.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/hash.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/hash.cc.s
.PHONY : tora/object/hash.cc.s

tora/object/int.o: tora/object/int.cc.o
.PHONY : tora/object/int.o

# target to build an object file
tora/object/int.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/int.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/int.cc.o
.PHONY : tora/object/int.cc.o

tora/object/int.i: tora/object/int.cc.i
.PHONY : tora/object/int.i

# target to preprocess a source file
tora/object/int.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/int.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/int.cc.i
.PHONY : tora/object/int.cc.i

tora/object/int.s: tora/object/int.cc.s
.PHONY : tora/object/int.s

# target to generate assembly for a file
tora/object/int.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/int.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/int.cc.s
.PHONY : tora/object/int.cc.s

tora/object/internals.o: tora/object/internals.cc.o
.PHONY : tora/object/internals.o

# target to build an object file
tora/object/internals.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/internals.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/internals.cc.o
.PHONY : tora/object/internals.cc.o

tora/object/internals.i: tora/object/internals.cc.i
.PHONY : tora/object/internals.i

# target to preprocess a source file
tora/object/internals.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/internals.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/internals.cc.i
.PHONY : tora/object/internals.cc.i

tora/object/internals.s: tora/object/internals.cc.s
.PHONY : tora/object/internals.s

# target to generate assembly for a file
tora/object/internals.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/internals.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/internals.cc.s
.PHONY : tora/object/internals.cc.s

tora/object/metaclass.o: tora/object/metaclass.cc.o
.PHONY : tora/object/metaclass.o

# target to build an object file
tora/object/metaclass.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/metaclass.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/metaclass.cc.o
.PHONY : tora/object/metaclass.cc.o

tora/object/metaclass.i: tora/object/metaclass.cc.i
.PHONY : tora/object/metaclass.i

# target to preprocess a source file
tora/object/metaclass.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/metaclass.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/metaclass.cc.i
.PHONY : tora/object/metaclass.cc.i

tora/object/metaclass.s: tora/object/metaclass.cc.s
.PHONY : tora/object/metaclass.s

# target to generate assembly for a file
tora/object/metaclass.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/metaclass.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/metaclass.cc.s
.PHONY : tora/object/metaclass.cc.s

tora/object/object.o: tora/object/object.cc.o
.PHONY : tora/object/object.o

# target to build an object file
tora/object/object.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/object.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/object.cc.o
.PHONY : tora/object/object.cc.o

tora/object/object.i: tora/object/object.cc.i
.PHONY : tora/object/object.i

# target to preprocess a source file
tora/object/object.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/object.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/object.cc.i
.PHONY : tora/object/object.cc.i

tora/object/object.s: tora/object/object.cc.s
.PHONY : tora/object/object.s

# target to generate assembly for a file
tora/object/object.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/object.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/object.cc.s
.PHONY : tora/object/object.cc.s

tora/object/re2_regexp_matched.o: tora/object/re2_regexp_matched.cc.o
.PHONY : tora/object/re2_regexp_matched.o

# target to build an object file
tora/object/re2_regexp_matched.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/re2_regexp_matched.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/re2_regexp_matched.cc.o
.PHONY : tora/object/re2_regexp_matched.cc.o

tora/object/re2_regexp_matched.i: tora/object/re2_regexp_matched.cc.i
.PHONY : tora/object/re2_regexp_matched.i

# target to preprocess a source file
tora/object/re2_regexp_matched.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/re2_regexp_matched.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/re2_regexp_matched.cc.i
.PHONY : tora/object/re2_regexp_matched.cc.i

tora/object/re2_regexp_matched.s: tora/object/re2_regexp_matched.cc.s
.PHONY : tora/object/re2_regexp_matched.s

# target to generate assembly for a file
tora/object/re2_regexp_matched.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/re2_regexp_matched.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/re2_regexp_matched.cc.s
.PHONY : tora/object/re2_regexp_matched.cc.s

tora/object/regexp.o: tora/object/regexp.cc.o
.PHONY : tora/object/regexp.o

# target to build an object file
tora/object/regexp.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/regexp.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/regexp.cc.o
.PHONY : tora/object/regexp.cc.o

tora/object/regexp.i: tora/object/regexp.cc.i
.PHONY : tora/object/regexp.i

# target to preprocess a source file
tora/object/regexp.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/regexp.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/regexp.cc.i
.PHONY : tora/object/regexp.cc.i

tora/object/regexp.s: tora/object/regexp.cc.s
.PHONY : tora/object/regexp.s

# target to generate assembly for a file
tora/object/regexp.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/regexp.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/regexp.cc.s
.PHONY : tora/object/regexp.cc.s

tora/object/stat.o: tora/object/stat.cc.o
.PHONY : tora/object/stat.o

# target to build an object file
tora/object/stat.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/stat.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/stat.cc.o
.PHONY : tora/object/stat.cc.o

tora/object/stat.i: tora/object/stat.cc.i
.PHONY : tora/object/stat.i

# target to preprocess a source file
tora/object/stat.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/stat.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/stat.cc.i
.PHONY : tora/object/stat.cc.i

tora/object/stat.s: tora/object/stat.cc.s
.PHONY : tora/object/stat.s

# target to generate assembly for a file
tora/object/stat.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/stat.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/stat.cc.s
.PHONY : tora/object/stat.cc.s

tora/object/str.o: tora/object/str.cc.o
.PHONY : tora/object/str.o

# target to build an object file
tora/object/str.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/str.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/str.cc.o
.PHONY : tora/object/str.cc.o

tora/object/str.i: tora/object/str.cc.i
.PHONY : tora/object/str.i

# target to preprocess a source file
tora/object/str.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/str.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/str.cc.i
.PHONY : tora/object/str.cc.i

tora/object/str.s: tora/object/str.cc.s
.PHONY : tora/object/str.s

# target to generate assembly for a file
tora/object/str.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/str.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/str.cc.s
.PHONY : tora/object/str.cc.s

tora/object/symbol.o: tora/object/symbol.cc.o
.PHONY : tora/object/symbol.o

# target to build an object file
tora/object/symbol.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/symbol.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/symbol.cc.o
.PHONY : tora/object/symbol.cc.o

tora/object/symbol.i: tora/object/symbol.cc.i
.PHONY : tora/object/symbol.i

# target to preprocess a source file
tora/object/symbol.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/symbol.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/symbol.cc.i
.PHONY : tora/object/symbol.cc.i

tora/object/symbol.s: tora/object/symbol.cc.s
.PHONY : tora/object/symbol.s

# target to generate assembly for a file
tora/object/symbol.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/symbol.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/symbol.cc.s
.PHONY : tora/object/symbol.cc.s

tora/object/time.o: tora/object/time.cc.o
.PHONY : tora/object/time.o

# target to build an object file
tora/object/time.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/time.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/time.cc.o
.PHONY : tora/object/time.cc.o

tora/object/time.i: tora/object/time.cc.i
.PHONY : tora/object/time.i

# target to preprocess a source file
tora/object/time.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/time.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/time.cc.i
.PHONY : tora/object/time.cc.i

tora/object/time.s: tora/object/time.cc.s
.PHONY : tora/object/time.s

# target to generate assembly for a file
tora/object/time.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/object/time.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/object/time.cc.s
.PHONY : tora/object/time.cc.s

tora/op.o: tora/op.cc.o
.PHONY : tora/op.o

# target to build an object file
tora/op.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/op.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/op.cc.o
.PHONY : tora/op.cc.o

tora/op.i: tora/op.cc.i
.PHONY : tora/op.i

# target to preprocess a source file
tora/op.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/op.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/op.cc.i
.PHONY : tora/op.cc.i

tora/op.s: tora/op.cc.s
.PHONY : tora/op.s

# target to generate assembly for a file
tora/op.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/op.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/op.cc.s
.PHONY : tora/op.cc.s

tora/operator.o: tora/operator.cc.o
.PHONY : tora/operator.o

# target to build an object file
tora/operator.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/operator.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/operator.cc.o
.PHONY : tora/operator.cc.o

tora/operator.i: tora/operator.cc.i
.PHONY : tora/operator.i

# target to preprocess a source file
tora/operator.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/operator.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/operator.cc.i
.PHONY : tora/operator.cc.i

tora/operator.s: tora/operator.cc.s
.PHONY : tora/operator.s

# target to generate assembly for a file
tora/operator.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/operator.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/operator.cc.s
.PHONY : tora/operator.cc.s

tora/ops.gen.o: tora/ops.gen.cc.o
.PHONY : tora/ops.gen.o

# target to build an object file
tora/ops.gen.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/ops.gen.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/ops.gen.cc.o
.PHONY : tora/ops.gen.cc.o

tora/ops.gen.i: tora/ops.gen.cc.i
.PHONY : tora/ops.gen.i

# target to preprocess a source file
tora/ops.gen.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/ops.gen.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/ops.gen.cc.i
.PHONY : tora/ops.gen.cc.i

tora/ops.gen.s: tora/ops.gen.cc.s
.PHONY : tora/ops.gen.s

# target to generate assembly for a file
tora/ops.gen.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/ops.gen.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/ops.gen.cc.s
.PHONY : tora/ops.gen.cc.s

tora/pad_list.o: tora/pad_list.cc.o
.PHONY : tora/pad_list.o

# target to build an object file
tora/pad_list.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/pad_list.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/pad_list.cc.o
.PHONY : tora/pad_list.cc.o

tora/pad_list.i: tora/pad_list.cc.i
.PHONY : tora/pad_list.i

# target to preprocess a source file
tora/pad_list.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/pad_list.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/pad_list.cc.i
.PHONY : tora/pad_list.cc.i

tora/pad_list.s: tora/pad_list.cc.s
.PHONY : tora/pad_list.s

# target to generate assembly for a file
tora/pad_list.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/pad_list.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/pad_list.cc.s
.PHONY : tora/pad_list.cc.s

tora/parser.o: tora/parser.cc.o
.PHONY : tora/parser.o

# target to build an object file
tora/parser.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/parser.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/parser.cc.o
.PHONY : tora/parser.cc.o

tora/parser.i: tora/parser.cc.i
.PHONY : tora/parser.i

# target to preprocess a source file
tora/parser.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/parser.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/parser.cc.i
.PHONY : tora/parser.cc.i

tora/parser.s: tora/parser.cc.s
.PHONY : tora/parser.s

# target to generate assembly for a file
tora/parser.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/parser.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/parser.cc.s
.PHONY : tora/parser.cc.s

tora/peek.o: tora/peek.cc.o
.PHONY : tora/peek.o

# target to build an object file
tora/peek.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/peek.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/peek.cc.o
.PHONY : tora/peek.cc.o

tora/peek.i: tora/peek.cc.i
.PHONY : tora/peek.i

# target to preprocess a source file
tora/peek.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/peek.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/peek.cc.i
.PHONY : tora/peek.cc.i

tora/peek.s: tora/peek.cc.s
.PHONY : tora/peek.s

# target to generate assembly for a file
tora/peek.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/peek.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/peek.cc.s
.PHONY : tora/peek.cc.s

tora/printf.o: tora/printf.cc.o
.PHONY : tora/printf.o

# target to build an object file
tora/printf.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/printf.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/printf.cc.o
.PHONY : tora/printf.cc.o

tora/printf.i: tora/printf.cc.i
.PHONY : tora/printf.i

# target to preprocess a source file
tora/printf.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/printf.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/printf.cc.i
.PHONY : tora/printf.cc.i

tora/printf.s: tora/printf.cc.s
.PHONY : tora/printf.s

# target to generate assembly for a file
tora/printf.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/printf.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/printf.cc.s
.PHONY : tora/printf.cc.s

tora/symbol_table.o: tora/symbol_table.cc.o
.PHONY : tora/symbol_table.o

# target to build an object file
tora/symbol_table.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/symbol_table.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/symbol_table.cc.o
.PHONY : tora/symbol_table.cc.o

tora/symbol_table.i: tora/symbol_table.cc.i
.PHONY : tora/symbol_table.i

# target to preprocess a source file
tora/symbol_table.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/symbol_table.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/symbol_table.cc.i
.PHONY : tora/symbol_table.cc.i

tora/symbol_table.s: tora/symbol_table.cc.s
.PHONY : tora/symbol_table.s

# target to generate assembly for a file
tora/symbol_table.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/symbol_table.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/symbol_table.cc.s
.PHONY : tora/symbol_table.cc.s

tora/symbols.gen.o: tora/symbols.gen.cc.o
.PHONY : tora/symbols.gen.o

# target to build an object file
tora/symbols.gen.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/symbols.gen.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/symbols.gen.cc.o
.PHONY : tora/symbols.gen.cc.o

tora/symbols.gen.i: tora/symbols.gen.cc.i
.PHONY : tora/symbols.gen.i

# target to preprocess a source file
tora/symbols.gen.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/symbols.gen.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/symbols.gen.cc.i
.PHONY : tora/symbols.gen.cc.i

tora/symbols.gen.s: tora/symbols.gen.cc.s
.PHONY : tora/symbols.gen.s

# target to generate assembly for a file
tora/symbols.gen.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/symbols.gen.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/symbols.gen.cc.s
.PHONY : tora/symbols.gen.cc.s

tora/token.gen.o: tora/token.gen.cc.o
.PHONY : tora/token.gen.o

# target to build an object file
tora/token.gen.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/token.gen.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/token.gen.cc.o
.PHONY : tora/token.gen.cc.o

tora/token.gen.i: tora/token.gen.cc.i
.PHONY : tora/token.gen.i

# target to preprocess a source file
tora/token.gen.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/token.gen.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/token.gen.cc.i
.PHONY : tora/token.gen.cc.i

tora/token.gen.s: tora/token.gen.cc.s
.PHONY : tora/token.gen.s

# target to generate assembly for a file
tora/token.gen.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/token.gen.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/token.gen.cc.s
.PHONY : tora/token.gen.cc.s

tora/util.o: tora/util.cc.o
.PHONY : tora/util.o

# target to build an object file
tora/util.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/util.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/util.cc.o
.PHONY : tora/util.cc.o

tora/util.i: tora/util.cc.i
.PHONY : tora/util.i

# target to preprocess a source file
tora/util.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/util.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/util.cc.i
.PHONY : tora/util.cc.i

tora/util.s: tora/util.cc.s
.PHONY : tora/util.s

# target to generate assembly for a file
tora/util.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/util.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/util.cc.s
.PHONY : tora/util.cc.s

tora/value.o: tora/value.cc.o
.PHONY : tora/value.o

# target to build an object file
tora/value.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value.cc.o
.PHONY : tora/value.cc.o

tora/value.i: tora/value.cc.i
.PHONY : tora/value.i

# target to preprocess a source file
tora/value.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value.cc.i
.PHONY : tora/value.cc.i

tora/value.s: tora/value.cc.s
.PHONY : tora/value.s

# target to generate assembly for a file
tora/value.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value.cc.s
.PHONY : tora/value.cc.s

tora/value/array.o: tora/value/array.cc.o
.PHONY : tora/value/array.o

# target to build an object file
tora/value/array.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/array.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/array.cc.o
.PHONY : tora/value/array.cc.o

tora/value/array.i: tora/value/array.cc.i
.PHONY : tora/value/array.i

# target to preprocess a source file
tora/value/array.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/array.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/array.cc.i
.PHONY : tora/value/array.cc.i

tora/value/array.s: tora/value/array.cc.s
.PHONY : tora/value/array.s

# target to generate assembly for a file
tora/value/array.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/array.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/array.cc.s
.PHONY : tora/value/array.cc.s

tora/value/bool.o: tora/value/bool.cc.o
.PHONY : tora/value/bool.o

# target to build an object file
tora/value/bool.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/bool.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/bool.cc.o
.PHONY : tora/value/bool.cc.o

tora/value/bool.i: tora/value/bool.cc.i
.PHONY : tora/value/bool.i

# target to preprocess a source file
tora/value/bool.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/bool.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/bool.cc.i
.PHONY : tora/value/bool.cc.i

tora/value/bool.s: tora/value/bool.cc.s
.PHONY : tora/value/bool.s

# target to generate assembly for a file
tora/value/bool.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/bool.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/bool.cc.s
.PHONY : tora/value/bool.cc.s

tora/value/bytes.o: tora/value/bytes.cc.o
.PHONY : tora/value/bytes.o

# target to build an object file
tora/value/bytes.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/bytes.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/bytes.cc.o
.PHONY : tora/value/bytes.cc.o

tora/value/bytes.i: tora/value/bytes.cc.i
.PHONY : tora/value/bytes.i

# target to preprocess a source file
tora/value/bytes.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/bytes.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/bytes.cc.i
.PHONY : tora/value/bytes.cc.i

tora/value/bytes.s: tora/value/bytes.cc.s
.PHONY : tora/value/bytes.s

# target to generate assembly for a file
tora/value/bytes.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/bytes.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/bytes.cc.s
.PHONY : tora/value/bytes.cc.s

tora/value/class.o: tora/value/class.cc.o
.PHONY : tora/value/class.o

# target to build an object file
tora/value/class.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/class.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/class.cc.o
.PHONY : tora/value/class.cc.o

tora/value/class.i: tora/value/class.cc.i
.PHONY : tora/value/class.i

# target to preprocess a source file
tora/value/class.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/class.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/class.cc.i
.PHONY : tora/value/class.cc.i

tora/value/class.s: tora/value/class.cc.s
.PHONY : tora/value/class.s

# target to generate assembly for a file
tora/value/class.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/class.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/class.cc.s
.PHONY : tora/value/class.cc.s

tora/value/code.o: tora/value/code.cc.o
.PHONY : tora/value/code.o

# target to build an object file
tora/value/code.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/code.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/code.cc.o
.PHONY : tora/value/code.cc.o

tora/value/code.i: tora/value/code.cc.i
.PHONY : tora/value/code.i

# target to preprocess a source file
tora/value/code.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/code.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/code.cc.i
.PHONY : tora/value/code.cc.i

tora/value/code.s: tora/value/code.cc.s
.PHONY : tora/value/code.s

# target to generate assembly for a file
tora/value/code.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/code.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/code.cc.s
.PHONY : tora/value/code.cc.s

tora/value/exception.o: tora/value/exception.cc.o
.PHONY : tora/value/exception.o

# target to build an object file
tora/value/exception.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/exception.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/exception.cc.o
.PHONY : tora/value/exception.cc.o

tora/value/exception.i: tora/value/exception.cc.i
.PHONY : tora/value/exception.i

# target to preprocess a source file
tora/value/exception.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/exception.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/exception.cc.i
.PHONY : tora/value/exception.cc.i

tora/value/exception.s: tora/value/exception.cc.s
.PHONY : tora/value/exception.s

# target to generate assembly for a file
tora/value/exception.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/exception.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/exception.cc.s
.PHONY : tora/value/exception.cc.s

tora/value/hash.o: tora/value/hash.cc.o
.PHONY : tora/value/hash.o

# target to build an object file
tora/value/hash.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/hash.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/hash.cc.o
.PHONY : tora/value/hash.cc.o

tora/value/hash.i: tora/value/hash.cc.i
.PHONY : tora/value/hash.i

# target to preprocess a source file
tora/value/hash.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/hash.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/hash.cc.i
.PHONY : tora/value/hash.cc.i

tora/value/hash.s: tora/value/hash.cc.s
.PHONY : tora/value/hash.s

# target to generate assembly for a file
tora/value/hash.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/hash.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/hash.cc.s
.PHONY : tora/value/hash.cc.s

tora/value/int.o: tora/value/int.cc.o
.PHONY : tora/value/int.o

# target to build an object file
tora/value/int.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/int.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/int.cc.o
.PHONY : tora/value/int.cc.o

tora/value/int.i: tora/value/int.cc.i
.PHONY : tora/value/int.i

# target to preprocess a source file
tora/value/int.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/int.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/int.cc.i
.PHONY : tora/value/int.cc.i

tora/value/int.s: tora/value/int.cc.s
.PHONY : tora/value/int.s

# target to generate assembly for a file
tora/value/int.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/int.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/int.cc.s
.PHONY : tora/value/int.cc.s

tora/value/object.o: tora/value/object.cc.o
.PHONY : tora/value/object.o

# target to build an object file
tora/value/object.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/object.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/object.cc.o
.PHONY : tora/value/object.cc.o

tora/value/object.i: tora/value/object.cc.i
.PHONY : tora/value/object.i

# target to preprocess a source file
tora/value/object.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/object.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/object.cc.i
.PHONY : tora/value/object.cc.i

tora/value/object.s: tora/value/object.cc.s
.PHONY : tora/value/object.s

# target to generate assembly for a file
tora/value/object.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/object.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/object.cc.s
.PHONY : tora/value/object.cc.s

tora/value/range.o: tora/value/range.cc.o
.PHONY : tora/value/range.o

# target to build an object file
tora/value/range.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/range.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/range.cc.o
.PHONY : tora/value/range.cc.o

tora/value/range.i: tora/value/range.cc.i
.PHONY : tora/value/range.i

# target to preprocess a source file
tora/value/range.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/range.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/range.cc.i
.PHONY : tora/value/range.cc.i

tora/value/range.s: tora/value/range.cc.s
.PHONY : tora/value/range.s

# target to generate assembly for a file
tora/value/range.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/range.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/range.cc.s
.PHONY : tora/value/range.cc.s

tora/value/regexp.o: tora/value/regexp.cc.o
.PHONY : tora/value/regexp.o

# target to build an object file
tora/value/regexp.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/regexp.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/regexp.cc.o
.PHONY : tora/value/regexp.cc.o

tora/value/regexp.i: tora/value/regexp.cc.i
.PHONY : tora/value/regexp.i

# target to preprocess a source file
tora/value/regexp.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/regexp.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/regexp.cc.i
.PHONY : tora/value/regexp.cc.i

tora/value/regexp.s: tora/value/regexp.cc.s
.PHONY : tora/value/regexp.s

# target to generate assembly for a file
tora/value/regexp.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/regexp.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/regexp.cc.s
.PHONY : tora/value/regexp.cc.s

tora/value/str.o: tora/value/str.cc.o
.PHONY : tora/value/str.o

# target to build an object file
tora/value/str.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/str.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/str.cc.o
.PHONY : tora/value/str.cc.o

tora/value/str.i: tora/value/str.cc.i
.PHONY : tora/value/str.i

# target to preprocess a source file
tora/value/str.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/str.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/str.cc.i
.PHONY : tora/value/str.cc.i

tora/value/str.s: tora/value/str.cc.s
.PHONY : tora/value/str.s

# target to generate assembly for a file
tora/value/str.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/value/str.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/value/str.cc.s
.PHONY : tora/value/str.cc.s

tora/vm.o: tora/vm.cc.o
.PHONY : tora/vm.o

# target to build an object file
tora/vm.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/vm.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/vm.cc.o
.PHONY : tora/vm.cc.o

tora/vm.i: tora/vm.cc.i
.PHONY : tora/vm.i

# target to preprocess a source file
tora/vm.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/vm.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/vm.cc.i
.PHONY : tora/vm.cc.i

tora/vm.s: tora/vm.cc.s
.PHONY : tora/vm.s

# target to generate assembly for a file
tora/vm.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/vm.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/vm.cc.s
.PHONY : tora/vm.cc.s

tora/vm.gen.o: tora/vm.gen.cc.o
.PHONY : tora/vm.gen.o

# target to build an object file
tora/vm.gen.cc.o:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/vm.gen.cc.o
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/vm.gen.cc.o
.PHONY : tora/vm.gen.cc.o

tora/vm.gen.i: tora/vm.gen.cc.i
.PHONY : tora/vm.gen.i

# target to preprocess a source file
tora/vm.gen.cc.i:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/vm.gen.cc.i
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/vm.gen.cc.i
.PHONY : tora/vm.gen.cc.i

tora/vm.gen.s: tora/vm.gen.cc.s
.PHONY : tora/vm.gen.s

# target to generate assembly for a file
tora/vm.gen.cc.s:
	$(MAKE) -f CMakeFiles/libtora_a.dir/build.make CMakeFiles/libtora_a.dir/tora/vm.gen.cc.s
	$(MAKE) -f CMakeFiles/libtora_so.dir/build.make CMakeFiles/libtora_so.dir/tora/vm.gen.cc.s
.PHONY : tora/vm.gen.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... lemon"
	@echo "... libtora_a"
	@echo "... libtora_so"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... tests/test_compiler.t"
	@echo "... tests/test_hexchar2int.t"
	@echo "... tests/test_inspector.t"
	@echo "... tests/test_lexer.t"
	@echo "... tests/test_lexical_frame.t"
	@echo "... tests/test_pad_list.t"
	@echo "... tests/test_split_package.t"
	@echo "... tests/test_value.t"
	@echo "... tests/test_value_array.t"
	@echo "... tests/test_value_code.t"
	@echo "... tests/test_value_op.t"
	@echo "... toraexe"
	@echo "... tests/test_compiler.o"
	@echo "... tests/test_compiler.i"
	@echo "... tests/test_compiler.s"
	@echo "... tests/test_hexchar2int.o"
	@echo "... tests/test_hexchar2int.i"
	@echo "... tests/test_hexchar2int.s"
	@echo "... tests/test_inspector.o"
	@echo "... tests/test_inspector.i"
	@echo "... tests/test_inspector.s"
	@echo "... tests/test_lexer.o"
	@echo "... tests/test_lexer.i"
	@echo "... tests/test_lexer.s"
	@echo "... tests/test_lexical_frame.o"
	@echo "... tests/test_lexical_frame.i"
	@echo "... tests/test_lexical_frame.s"
	@echo "... tests/test_pad_list.o"
	@echo "... tests/test_pad_list.i"
	@echo "... tests/test_pad_list.s"
	@echo "... tests/test_split_package.o"
	@echo "... tests/test_split_package.i"
	@echo "... tests/test_split_package.s"
	@echo "... tests/test_value.o"
	@echo "... tests/test_value.i"
	@echo "... tests/test_value.s"
	@echo "... tests/test_value_array.o"
	@echo "... tests/test_value_array.i"
	@echo "... tests/test_value_array.s"
	@echo "... tests/test_value_code.o"
	@echo "... tests/test_value_code.i"
	@echo "... tests/test_value_code.s"
	@echo "... tests/test_value_op.o"
	@echo "... tests/test_value_op.i"
	@echo "... tests/test_value_op.s"
	@echo "... tools/lemon/lemon.o"
	@echo "... tools/lemon/lemon.i"
	@echo "... tools/lemon/lemon.s"
	@echo "... tora/builtin.o"
	@echo "... tora/builtin.i"
	@echo "... tora/builtin.s"
	@echo "... tora/compiler.o"
	@echo "... tora/compiler.i"
	@echo "... tora/compiler.s"
	@echo "... tora/disasm.o"
	@echo "... tora/disasm.i"
	@echo "... tora/disasm.s"
	@echo "... tora/frame.o"
	@echo "... tora/frame.i"
	@echo "... tora/frame.s"
	@echo "... tora/inspector.o"
	@echo "... tora/inspector.i"
	@echo "... tora/inspector.s"
	@echo "... tora/lexer.gen.o"
	@echo "... tora/lexer.gen.i"
	@echo "... tora/lexer.gen.s"
	@echo "... tora/main.o"
	@echo "... tora/main.i"
	@echo "... tora/main.s"
	@echo "... tora/node.o"
	@echo "... tora/node.i"
	@echo "... tora/node.s"
	@echo "... tora/nodes.gen.o"
	@echo "... tora/nodes.gen.i"
	@echo "... tora/nodes.gen.s"
	@echo "... tora/object.o"
	@echo "... tora/object.i"
	@echo "... tora/object.s"
	@echo "... tora/object/array.o"
	@echo "... tora/object/array.i"
	@echo "... tora/object/array.s"
	@echo "... tora/object/bytes.o"
	@echo "... tora/object/bytes.i"
	@echo "... tora/object/bytes.s"
	@echo "... tora/object/caller.o"
	@echo "... tora/object/caller.i"
	@echo "... tora/object/caller.s"
	@echo "... tora/object/class.o"
	@echo "... tora/object/class.i"
	@echo "... tora/object/class.s"
	@echo "... tora/object/code.o"
	@echo "... tora/object/code.i"
	@echo "... tora/object/code.s"
	@echo "... tora/object/dir.o"
	@echo "... tora/object/dir.i"
	@echo "... tora/object/dir.s"
	@echo "... tora/object/double.o"
	@echo "... tora/object/double.i"
	@echo "... tora/object/double.s"
	@echo "... tora/object/dynaloader.o"
	@echo "... tora/object/dynaloader.i"
	@echo "... tora/object/dynaloader.s"
	@echo "... tora/object/env.o"
	@echo "... tora/object/env.i"
	@echo "... tora/object/env.s"
	@echo "... tora/object/file.o"
	@echo "... tora/object/file.i"
	@echo "... tora/object/file.s"
	@echo "... tora/object/file_package.o"
	@echo "... tora/object/file_package.i"
	@echo "... tora/object/file_package.s"
	@echo "... tora/object/hash.o"
	@echo "... tora/object/hash.i"
	@echo "... tora/object/hash.s"
	@echo "... tora/object/int.o"
	@echo "... tora/object/int.i"
	@echo "... tora/object/int.s"
	@echo "... tora/object/internals.o"
	@echo "... tora/object/internals.i"
	@echo "... tora/object/internals.s"
	@echo "... tora/object/metaclass.o"
	@echo "... tora/object/metaclass.i"
	@echo "... tora/object/metaclass.s"
	@echo "... tora/object/object.o"
	@echo "... tora/object/object.i"
	@echo "... tora/object/object.s"
	@echo "... tora/object/re2_regexp_matched.o"
	@echo "... tora/object/re2_regexp_matched.i"
	@echo "... tora/object/re2_regexp_matched.s"
	@echo "... tora/object/regexp.o"
	@echo "... tora/object/regexp.i"
	@echo "... tora/object/regexp.s"
	@echo "... tora/object/stat.o"
	@echo "... tora/object/stat.i"
	@echo "... tora/object/stat.s"
	@echo "... tora/object/str.o"
	@echo "... tora/object/str.i"
	@echo "... tora/object/str.s"
	@echo "... tora/object/symbol.o"
	@echo "... tora/object/symbol.i"
	@echo "... tora/object/symbol.s"
	@echo "... tora/object/time.o"
	@echo "... tora/object/time.i"
	@echo "... tora/object/time.s"
	@echo "... tora/op.o"
	@echo "... tora/op.i"
	@echo "... tora/op.s"
	@echo "... tora/operator.o"
	@echo "... tora/operator.i"
	@echo "... tora/operator.s"
	@echo "... tora/ops.gen.o"
	@echo "... tora/ops.gen.i"
	@echo "... tora/ops.gen.s"
	@echo "... tora/pad_list.o"
	@echo "... tora/pad_list.i"
	@echo "... tora/pad_list.s"
	@echo "... tora/parser.o"
	@echo "... tora/parser.i"
	@echo "... tora/parser.s"
	@echo "... tora/peek.o"
	@echo "... tora/peek.i"
	@echo "... tora/peek.s"
	@echo "... tora/printf.o"
	@echo "... tora/printf.i"
	@echo "... tora/printf.s"
	@echo "... tora/symbol_table.o"
	@echo "... tora/symbol_table.i"
	@echo "... tora/symbol_table.s"
	@echo "... tora/symbols.gen.o"
	@echo "... tora/symbols.gen.i"
	@echo "... tora/symbols.gen.s"
	@echo "... tora/token.gen.o"
	@echo "... tora/token.gen.i"
	@echo "... tora/token.gen.s"
	@echo "... tora/util.o"
	@echo "... tora/util.i"
	@echo "... tora/util.s"
	@echo "... tora/value.o"
	@echo "... tora/value.i"
	@echo "... tora/value.s"
	@echo "... tora/value/array.o"
	@echo "... tora/value/array.i"
	@echo "... tora/value/array.s"
	@echo "... tora/value/bool.o"
	@echo "... tora/value/bool.i"
	@echo "... tora/value/bool.s"
	@echo "... tora/value/bytes.o"
	@echo "... tora/value/bytes.i"
	@echo "... tora/value/bytes.s"
	@echo "... tora/value/class.o"
	@echo "... tora/value/class.i"
	@echo "... tora/value/class.s"
	@echo "... tora/value/code.o"
	@echo "... tora/value/code.i"
	@echo "... tora/value/code.s"
	@echo "... tora/value/exception.o"
	@echo "... tora/value/exception.i"
	@echo "... tora/value/exception.s"
	@echo "... tora/value/hash.o"
	@echo "... tora/value/hash.i"
	@echo "... tora/value/hash.s"
	@echo "... tora/value/int.o"
	@echo "... tora/value/int.i"
	@echo "... tora/value/int.s"
	@echo "... tora/value/object.o"
	@echo "... tora/value/object.i"
	@echo "... tora/value/object.s"
	@echo "... tora/value/range.o"
	@echo "... tora/value/range.i"
	@echo "... tora/value/range.s"
	@echo "... tora/value/regexp.o"
	@echo "... tora/value/regexp.i"
	@echo "... tora/value/regexp.s"
	@echo "... tora/value/str.o"
	@echo "... tora/value/str.i"
	@echo "... tora/value/str.s"
	@echo "... tora/vm.o"
	@echo "... tora/vm.i"
	@echo "... tora/vm.s"
	@echo "... tora/vm.gen.o"
	@echo "... tora/vm.gen.i"
	@echo "... tora/vm.gen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

