/* Generated by re2c 0.13.5 on Sat Apr  7 23:36:28 2012 */
/* vim: set filetype=cpp: */
/**
 * This is yet another IRC protocol parser.
 * Copyright (C) 2012 Tokuhiro Matsuno.
 *
 * http://tokuhirom.mit-license.org/
 */

/**
 * SEE http://tools.ietf.org/html/rfc1459#page-8 for protocol details.
 */

#include <string>
#include <vector>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define NANOIRCPARSER_MESSAGE_IS_PARTIAL -2
#define NANOIRCPARSER_PARSE_FAILED -2

class NanoIRCParser {
public:
    struct Message {
        std::string prefix;
        std::string command;
        std::vector<std::string> params;
    };

    int parse(
        std::string src,
        Message &msg) {

        char *cursor = (char*)src.c_str();
        char *orig = cursor;
        char *marker = cursor;
        char *mark2 = cursor;
        
    

        /*
        * Note. fix HOST regexp to better one.
        */

#define NNMARK(x) do { \
        std::string text(mark2, cursor-mark2); \
        msg.x = text; \
    } while(0)

        mark2 = cursor;
    
	{
		char yych;

		yych = (char)*cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy6;
		case ':':	goto yy2;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy4;
		default:	goto yy8;
		}
yy2:
		++cursor;
		{
            // ":" prefix SPACE
            goto prefix;
        }
yy4:
		++cursor;
		yych = (char)*cursor;
		goto yy13;
yy5:
		{
            NNMARK(command);
            goto params_space;
        }
yy6:
		yych = (char)*(marker = ++cursor);
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy9;
		default:	goto yy7;
		}
yy7:
		{ return return_error(src); }
yy8:
		yych = (char)*++cursor;
		goto yy7;
yy9:
		yych = (char)*++cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy11;
		default:	goto yy10;
		}
yy10:
		cursor = marker;
		goto yy7;
yy11:
		yych = (char)*++cursor;
		goto yy5;
yy12:
		++cursor;
		yych = (char)*cursor;
yy13:
		switch (yych) {
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy12;
		default:	goto yy5;
		}
	}


    command_only:
        mark2 = cursor;
    
	{
		char yych;
		yych = (char)*cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy18;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy16;
		default:	goto yy20;
		}
yy16:
		++cursor;
		yych = (char)*cursor;
		goto yy25;
yy17:
		{
            NNMARK(command);
            goto params_space;
        }
yy18:
		yych = (char)*(marker = ++cursor);
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy21;
		default:	goto yy19;
		}
yy19:
		{ return return_error(src); }
yy20:
		yych = (char)*++cursor;
		goto yy19;
yy21:
		yych = (char)*++cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy23;
		default:	goto yy22;
		}
yy22:
		cursor = marker;
		goto yy19;
yy23:
		yych = (char)*++cursor;
		goto yy17;
yy24:
		++cursor;
		yych = (char)*cursor;
yy25:
		switch (yych) {
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy24;
		default:	goto yy17;
		}
	}


    prefix:
        // PREFIX = SERVERNAME | NICK ("!" USER)? ("@" HOST)?
        mark2 = cursor;
    
	{
		char yych;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '.':
		case '8':
		case '9':	goto yy32;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy31;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':	goto yy28;
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy30;
		default:	goto yy33;
		}
yy28:
		yych = (char)*(marker = ++cursor);
		goto yy50;
yy29:
		{
            NNMARK(prefix);
            goto prefix_space;
        }
yy30:
		yych = (char)*(marker = ++cursor);
		goto yy48;
yy31:
		yych = (char)*++cursor;
		switch (yych) {
		case '.':	goto yy37;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy38;
		default:	goto yy36;
		}
yy32:
		yych = (char)*++cursor;
		goto yy36;
yy33:
		++cursor;
		{ return return_error(src); }
yy35:
		++cursor;
		yych = (char)*cursor;
yy36:
		switch (yych) {
		case '-':
		case '.':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy35;
		default:	goto yy29;
		}
yy37:
		yych = (char)*++cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy40;
		default:	goto yy36;
		}
yy38:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy35;
		case '.':	goto yy37;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy38;
		default:	goto yy29;
		}
yy40:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy35;
		case '.':	goto yy42;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy40;
		default:	goto yy29;
		}
yy42:
		yych = (char)*++cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy43;
		default:	goto yy36;
		}
yy43:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy35;
		case '.':	goto yy45;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy43;
		default:	goto yy29;
		}
yy45:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '.':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy35;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy45;
		default:	goto yy29;
		}
yy47:
		marker = ++cursor;
		yych = (char)*cursor;
yy48:
		switch (yych) {
		case '!':	goto yy51;
		case '-':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy47;
		case '.':	goto yy35;
		case '@':	goto yy53;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '}':	goto yy49;
		default:	goto yy29;
		}
yy49:
		marker = ++cursor;
		yych = (char)*cursor;
yy50:
		switch (yych) {
		case '!':	goto yy51;
		case '-':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '}':	goto yy49;
		case '@':	goto yy53;
		default:	goto yy29;
		}
yy51:
		yych = (char)*++cursor;
		switch (yych) {
		case ' ':	goto yy52;
		default:	goto yy66;
		}
yy52:
		cursor = marker;
		goto yy29;
yy53:
		yych = (char)*++cursor;
		switch (yych) {
		case '-':
		case '.':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy56;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy54;
		default:	goto yy52;
		}
yy54:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy56;
		case '.':	goto yy58;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy54;
		default:	goto yy29;
		}
yy56:
		++cursor;
		yych = (char)*cursor;
yy57:
		switch (yych) {
		case '-':
		case '.':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy56;
		default:	goto yy29;
		}
yy58:
		yych = (char)*++cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy59;
		default:	goto yy57;
		}
yy59:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy56;
		case '.':	goto yy61;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy59;
		default:	goto yy29;
		}
yy61:
		yych = (char)*++cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy62;
		default:	goto yy57;
		}
yy62:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy56;
		case '.':	goto yy64;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy62;
		default:	goto yy29;
		}
yy64:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '.':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy56;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy64;
		default:	goto yy29;
		}
yy66:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy29;
		case '@':	goto yy68;
		default:	goto yy66;
		}
yy68:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy29;
		case '-':
		case '.':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy70;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy72;
		case '@':	goto yy68;
		default:	goto yy66;
		}
yy70:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy29;
		case '-':
		case '.':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy70;
		case '@':	goto yy68;
		default:	goto yy66;
		}
yy72:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy29;
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy70;
		case '.':	goto yy74;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy72;
		case '@':	goto yy68;
		default:	goto yy66;
		}
yy74:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy29;
		case '-':
		case '.':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy70;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy75;
		case '@':	goto yy68;
		default:	goto yy66;
		}
yy75:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy29;
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy70;
		case '.':	goto yy77;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy75;
		case '@':	goto yy68;
		default:	goto yy66;
		}
yy77:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy29;
		case '-':
		case '.':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy70;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy78;
		case '@':	goto yy68;
		default:	goto yy66;
		}
yy78:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy29;
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy70;
		case '.':	goto yy80;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy78;
		case '@':	goto yy68;
		default:	goto yy66;
		}
yy80:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy29;
		case '-':
		case '.':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy70;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy80;
		case '@':	goto yy68;
		default:	goto yy66;
		}
	}


#undef NNMARK

    prefix_space:
    
	{
		char yych;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy84;
		default:	goto yy86;
		}
yy84:
		++cursor;
		yych = (char)*cursor;
		goto yy89;
yy85:
		{
            goto command_only;
        }
yy86:
		++cursor;
		{ return return_error(src); }
yy88:
		++cursor;
		yych = (char)*cursor;
yy89:
		switch (yych) {
		case ' ':	goto yy88;
		default:	goto yy85;
		}
	}


    params_space:
    
	{
		char yych;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy92;
		default:	goto yy94;
		}
yy92:
		++cursor;
		yych = (char)*cursor;
		goto yy97;
yy93:
		{
            goto params;
        }
yy94:
		++cursor;
		{ return return_error(src); }
yy96:
		++cursor;
		yych = (char)*cursor;
yy97:
		switch (yych) {
		case ' ':	goto yy96;
		default:	goto yy93;
		}
	}


    after_params_middle:
    
	{
		char yych;
		yych = (char)*cursor;
		switch (yych) {
		case '\r':	goto yy102;
		case ' ':	goto yy100;
		default:	goto yy104;
		}
yy100:
		++cursor;
		yych = (char)*cursor;
		goto yy108;
yy101:
		{
            goto params;
        }
yy102:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '\n':	goto yy105;
		default:	goto yy103;
		}
yy103:
		{ return return_error(src); }
yy104:
		yych = (char)*++cursor;
		goto yy103;
yy105:
		++cursor;
		{
            goto success;
        }
yy107:
		++cursor;
		yych = (char)*cursor;
yy108:
		switch (yych) {
		case ' ':	goto yy107;
		default:	goto yy101;
		}
	}


    params:
        // <params>   ::= <SPACE> [ ':' <trailing> | <middle> <params> ]
        mark2 = cursor;
    
	{
		char yych;
		yych = (char)*cursor;
		switch (yych) {
		case ':':	goto yy111;
		default:	goto yy113;
		}
yy111:
		++cursor;
		yych = (char)*cursor;
		goto yy118;
yy112:
		{
            std::string text(mark2+1, cursor-mark2-1);
            msg.params.push_back(text);
            goto crlf;
        }
yy113:
		++cursor;
		yych = (char)*cursor;
		goto yy116;
yy114:
		{
            std::string text(mark2, cursor-mark2);
            msg.params.push_back(text);
            goto after_params_middle;
        }
yy115:
		++cursor;
		yych = (char)*cursor;
yy116:
		switch (yych) {
		case '\n':
		case '\r':
		case ' ':	goto yy114;
		default:	goto yy115;
		}
yy117:
		++cursor;
		yych = (char)*cursor;
yy118:
		switch (yych) {
		case 0x00:
		case '\n':
		case '\r':	goto yy112;
		default:	goto yy117;
		}
	}


    crlf:
        mark2 = cursor;
    
	{
		char yych;
		yych = (char)*cursor;
		switch (yych) {
		case '\r':	goto yy121;
		default:	goto yy123;
		}
yy121:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '\n':	goto yy124;
		default:	goto yy122;
		}
yy122:
		{
            return return_error(src);
        }
yy123:
		yych = (char)*++cursor;
		goto yy122;
yy124:
		++cursor;
		{
            goto success;
        }
	}

    success:
        return cursor-orig;
    }

    int return_error(const std::string &src) {
        return memchr(src.c_str(), '\015', src.size()) == NULL ? NANOIRCPARSER_MESSAGE_IS_PARTIAL : NANOIRCPARSER_PARSE_FAILED;
    }
};

