#ifndef TORA_EXCEPTION_H_
#define TORA_EXCEPTION_H_

typedef enum {
  EXCEPTION_TYPE_UNDEF,
  EXCEPTION_TYPE_STOP_ITERATION,
  EXCEPTION_TYPE_ZERO_DIVIDED,
  EXCEPTION_TYPE_GENERAL,
  EXCEPTION_TYPE_ARGUMENT,
  EXCEPTION_TYPE_ERRNO,
} exception_type_t;

#endif // TORA_EXCEPTION_H_
