import os

import os
import json
from glob import glob

conf = json.loads(open('../../config.json').read())

if os.name == 'nt':
    libs = conf['LIBS'] + ['uv', 'psapi', 'iphlpapi', 'pthread']
else:
    libs = conf['LIBS']

env = Environment(
    CXXFLAGS=conf['CXXFLAGS'],
    CCFLAGS=conf['CCFLAGS'],
    LINKFLAGS=conf['LINKFLAGS'],
    CC=conf['CC'],
    CXX=conf['CXX'],
    SHLIBPREFIX=conf['SHLIBPREFIX'],
    LIBS=libs,
    tools=conf['TOOLS'],
)

shlib = env.SharedLibrary("lib/UV_" + conf['TORA_EXTSUFFIX'], ['uv.cc'], SHLIBPREFIX='', LIBPATH=['../..'], LIBS=libs)
Default(shlib)

env.Command('test', shlib, '../../bin/tora -I lib -I ../../lib/ t/uv.tra')

installs = []
for x in os.listdir('lib/'):
    dst = conf['TORA_LIBPREFIX'] + x
    src = "lib/" + x
    installs += [env.InstallAs(dst, src)]

env.Alias('install', [shlib, installs])
