import os

import os
import json
from glob import glob

conf = json.loads(open('../../config.json').read())

libs = conf['LIBS']
if os.name == 'nt':
    libs += ['curldll']
else:
    libs += ['curl']

env = Environment(
    ENV={'PATH': conf['PATH']},
    CXXFLAGS=conf['CXXFLAGS'],
    CCFLAGS=conf['CCFLAGS'],
    LINKFLAGS=conf['LINKFLAGS'],
    CPPPATH=conf['CPPPATH'],
    CC=conf['CC'],
    CXX=conf['CXX'],
    SHLIBPREFIX=conf['SHLIBPREFIX'],
    LIBS=libs,
    tools=conf['TOOLS'],
)

shlib = env.SharedLibrary("lib/Curl" + conf['TORA_EXTSUFFIX'], ['curl.cc'], SHLIBPREFIX='', LIBPATH=['../..'])
Default(shlib)

env.Command('test', shlib, '../../bin/tora -I lib -I ../../lib/ t/curl.tra')

installs = []
for x in os.listdir('lib/'):
    dst = conf['TORA_LIBPREFIX'] + x
    src = "lib/" + x
    installs += [env.InstallAs(dst, src)]

env.Alias('install', [shlib, installs])
